export const proStructure = {
  computer: `src/
  app/
    layout
    page
    loading
    error
    not-found
    (auth)/
      login/
        page
      register/
        page
      layout
    (shop)/
      products/
        page
        loading
        [productId]/
          page
          layout
      categories/
        page
        [categoryId]/
          page
      layout
    (checkout)/
      cart/
        page
      checkout/
        page
      layout
    (dashboard)/
      account/
        page
      orders/
        page
        [orderId]/
          page
      layout
    api/
      auth/
        [...nextauth]/
          route
      products/
        route
        [productId]/
          route
      orders/
        route
  components/
    ui/
      button
      input
      card
      modal
    layout/
      header
      footer
      navigation
    products/
      product-card
      product-grid
      product-filters
    checkout/
      cart-item
      payment-form
  lib/
    db/
      prisma
      schema.prisma
    utils/
      formatting
      validation
    config/
      site
  hooks/
    use-cart
    use-products
    use-search
  types/
    product
    order
    user
  public/
    images/
      products/
      banners/
    icons/
  middleware
  `,
  email_saaa: `src/
  app/
    layoutx
    pagex
    loadingx
    errorx
    not-foundx
    (auth)/
      login/
        pagex
      register/
        pagex
      forgot-password/
        pagex
      layoutx
    (dashboard)/
      layoutx
      pagex
      campaigns/
        pagex
        loadingx
        create/
          pagex
        [campaignId]/
          pagex
          edit/
            pagex
          analytics/
            pagex
      templates/
        pagex
        create/
          pagex
        [templateId]/
          pagex
          edit/
            pagex
      subscribers/
        pagex
        import/
          pagex
        [subscriberId]/
          pagex
      analytics/
        pagex
        overview/
          pagex
        engagement/
          pagex
        deliverability/
          pagex
      settings/
        pagex
        profile/
          pagex
        team/
          pagex
        billing/
          pagex
        integrations/
          pagex
    api/
      auth/
        [...nextauth]/
          route
      campaigns/
        route
        [campaignId]/
          route
          send/
            route
      templates/
        route
        [templateId]/
          route
      subscribers/
        route
        import/
          route
        [subscriberId]/
          route
      webhooks/
        mailgun/
          route
        stripe/
          route
  components/
    ui/
      buttonx
      inputx
      selectx
      modalx
      dropdownx
      data-tablex
    email-editor/
      editorx
      toolbarx
      blocks/
        text-blockx
        image-blockx
        button-blockx
      previewx
    analytics/
      metrics-cardx
      line-chartx
      pie-chartx
      heat-mapx
    campaigns/
      campaign-cardx
      campaign-listx
      campaign-statsx
      schedule-formx
    layout/
      headerx
      sidebarx
      footerx
      navigationx
  lib/
    db/
      prisma
      schema.prisma
    email/
      send
      template-parser
      validators
    services/
      mailgun
      stripe
      analytics
    utils/
      formatting
      validation
      dates
  hooks/
    use-campaigns
    use-templates
    use-subscribers
    use-analytics
    use-pagination
  types/
    campaign
    template
    subscriber
    analytics
    user
  config/
    site
    constants
  styles/
    editor.css
    globals.css
  middleware
  `,
};
